### ISSUE TITLE
The question on the OA 

### ISSUE THREAD

**Issue by Jingwen-Yuan** [meixiaoguang/SSAN#1]
Thank you sharing the code.
But after running the project with the same Parameter Setting, I just gain the OA about 0.94 in the test of Pavia Center Dataset. Could you tell me how to reach the same OA like you or maybe I have something wrong with the parameter settings?
Thank you very much

**Comment by meixiaoguang** [comment]
I have updated the files, please check them.

**Comment by Jingwen-Yuan** [comment]
Thank you for your updating. I've run the new ssan.py again on 2080Ti GPU more than three times, but the valid accuracy still around 0.4 and it even cannot reach the the best valid accuracy of 0.8. Is there anything wrong with my manipulation?
Thank you!
